import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { notify } from "@/lib/notify";
import { ShieldAlert, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

function formatBytes(bytes: number) { if (!bytes) return "0 B"; const units = ["B", "KB", "MB", "GB", "TB"]; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}`; }

export default function AdminPage() {
  const { user } = useAuth(); const users = trpc.backup.admin.users.useQuery(undefined, { enabled: user?.role === "admin" }); const settings = trpc.backup.admin.settings.useQuery(undefined, { enabled: user?.role === "admin" });
  const [backupsEnabled, setBackupsEnabled] = useState(true); const [maxUploadMegabytes, setMaxUploadMegabytes] = useState("50");
  useEffect(() => { if (settings.data) { setBackupsEnabled(settings.data.backupsEnabled); setMaxUploadMegabytes(String(settings.data.maxUploadMegabytes)); } }, [settings.data]);
  const update = trpc.backup.admin.updateSettings.useMutation({ onSuccess: () => { settings.refetch(); notify.success("System settings saved", "The backup policy now applies across the workspace."); }, onError: error => notify.error("System settings could not be saved", error.message) });
  if (user?.role !== "admin") return <div className="mx-auto flex min-h-[55vh] max-w-xl flex-col items-center justify-center text-center"><div className="rounded-2xl bg-[#fff2f0] p-4 text-[#b94640]"><ShieldAlert className="h-7 w-7" /></div><h1 className="mt-5 text-2xl font-semibold text-[#28364b]">Owner access required</h1><p className="mt-2 text-sm leading-6 text-[#7d8a9d]">This area is reserved for the workspace owner to monitor users and apply system-wide backup controls.</p></div>;
  return <div className="mx-auto w-full max-w-7xl space-y-6"><div><p className="text-xs font-bold tracking-[0.14em] text-[#7291b9] uppercase">Owner controls</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em] text-[#1d2939]">Administration</h1><p className="mt-2 text-sm text-[#748196]">Monitor user storage and manage system-wide backup availability.</p></div><section className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><Card className="border-[#e2e8f0] shadow-sm"><CardContent className="p-0"><div className="flex items-center gap-3 px-6 py-5"><div className="rounded-xl bg-[#eef4ff] p-2.5 text-[#2460a1]"><UsersRound className="h-5 w-5" /></div><div><h2 className="font-semibold text-[#2a394d]">User storage</h2><p className="text-sm text-[#7c899d]">Current managed-file storage by account.</p></div></div><div className="overflow-x-auto border-t border-[#edf0f4]"><table className="w-full text-left text-sm"><thead className="bg-[#fbfcfe] text-xs uppercase tracking-wide text-[#8491a3]"><tr><th className="px-6 py-3 font-medium">User</th><th className="px-5 py-3 font-medium">Files</th><th className="px-5 py-3 font-medium">Storage</th><th className="px-6 py-3 font-medium">Role</th></tr></thead><tbody>{users.data?.map(person => <tr key={person.id} className="border-t border-[#f0f2f5]"><td className="px-6 py-4"><p className="font-medium text-[#344258]">{person.name || "Unnamed user"}</p><p className="mt-0.5 text-xs text-[#8996a8]">{person.email || "No email available"}</p></td><td className="px-5 py-4 text-[#66758b]">{person.fileCount}</td><td className="px-5 py-4 font-medium text-[#425269]">{formatBytes(Number(person.storageBytes))}</td><td className="px-6 py-4"><Badge variant="secondary" className="capitalize">{person.role}</Badge></td></tr>)}</tbody></table></div></CardContent></Card><Card className="border-[#e2e8f0] shadow-sm"><CardContent className="p-6"><h2 className="font-semibold text-[#2a394d]">System backup settings</h2><p className="mt-1 text-sm leading-6 text-[#7c899d]">These controls apply to every user-managed backup operation.</p><div className="mt-6 flex items-center justify-between rounded-xl border border-[#e6ebf1] p-4"><div><p className="text-sm font-medium text-[#425168]">Backups enabled</p><p className="mt-1 text-xs text-[#8995a7]">Allow new uploads and scheduled snapshots.</p></div><Switch checked={backupsEnabled} onCheckedChange={setBackupsEnabled} /></div><div className="mt-5 space-y-2"><Label htmlFor="max-upload">Maximum upload size (MB)</Label><Input id="max-upload" type="number" min="1" max="50" value={maxUploadMegabytes} onChange={event => setMaxUploadMegabytes(event.target.value)} /></div><Button className="mt-6 w-full" disabled={update.isPending} onClick={() => update.mutate({ backupsEnabled, maxUploadMegabytes: Number(maxUploadMegabytes) })}>Save settings</Button></CardContent></Card></section></div>;
}
