import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { notify } from "@/lib/notify";
import { trpc } from "@/lib/trpc";
import { Clipboard, Laptop, Link2, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";

type Pairing = { device: { id: number; name: string; createdAt: Date }; deviceToken: string; encryptionKey: string; encryptionAlgorithm: string };

export default function CompanionPage() {
  const devices = trpc.backup.companion.listDevices.useQuery();
  const utils = trpc.useUtils();
  const revoke = trpc.backup.companion.revokeDevice.useMutation({ onSuccess: () => { utils.backup.companion.listDevices.invalidate(); notify.success("Local device revoked", "The companion can no longer synchronize or restore encrypted files."); }, onError: error => notify.error("Device could not be revoked", error.message) });
  return <div className="mx-auto w-full max-w-7xl space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold tracking-[0.14em] text-[#7291b9] uppercase">Local companion</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em] text-[#1d2939]">Folder synchronization</h1><p className="mt-2 max-w-2xl text-sm text-[#748196]">Pair a local folder companion to detect changes and encrypt every file before it leaves your machine.</p></div><PairDevice onPaired={() => utils.backup.companion.listDevices.invalidate()} /></div><section className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><Card className="border-[#dbe6f2] bg-[#f8fbff] shadow-sm"><CardContent className="p-6"><div className="rounded-2xl bg-[#e7f2ff] p-3 text-[#235f9f] w-fit"><ShieldCheck className="h-5 w-5" /></div><h2 className="mt-5 font-semibold text-[#2a394d]">Client-side protection</h2><p className="mt-2 text-sm leading-6 text-[#718096]">Each paired device receives its own encryption key. The companion encrypts local content before transfer, so cloud storage receives only ciphertext.</p><div className="mt-6 space-y-3 text-sm text-[#53647a]"><p className="flex gap-3"><Link2 className="mt-0.5 h-4 w-4 text-[#2b70b8]" /> Pair using a one-time configuration file.</p><p className="flex gap-3"><Laptop className="mt-0.5 h-4 w-4 text-[#2b70b8]" /> Watch a local folder or run a single sync.</p></div></CardContent></Card><Card className="border-[#e2e8f0] shadow-sm"><CardContent className="p-0">{devices.data?.length ? <div className="divide-y divide-[#edf0f4]">{devices.data.map(device => <div key={device.id} className="flex items-center gap-4 px-5 py-5"><div className="rounded-xl bg-[#eef4ff] p-3 text-[#2d6bac]"><Laptop className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-medium text-[#344258]">{device.name}</p><p className="mt-1 text-xs text-[#8190a4]">{device.lastSyncedAt ? `Last synced ${new Date(device.lastSyncedAt).toLocaleString()}` : `Paired ${new Date(device.createdAt).toLocaleString()}`}</p></div><Button size="icon" variant="ghost" className="text-[#b64943] hover:bg-[#fff2f0] hover:text-[#b64943]" onClick={() => revoke.mutate({ deviceId: device.id })} aria-label="Revoke local device"><Trash2 className="h-4 w-4" /></Button></div>)}</div> : <div className="py-16 text-center"><Laptop className="mx-auto h-8 w-8 text-[#9da9b9]" /><p className="mt-4 font-medium text-[#45546a]">No local devices paired.</p><p className="mt-1 text-sm text-[#8592a5]">Create a pairing file to activate a selected local folder.</p></div>}</CardContent></Card></section></div>;
}

function PairDevice({ onPaired }: { onPaired: () => void }) {
  const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [pairing, setPairing] = useState<Pairing | null>(null);
  const create = trpc.backup.companion.createDevice.useMutation({ onSuccess: result => { setPairing(result); onPaired(); notify.success("Local device paired", "Copy the pairing file to the computer that will monitor your folder."); }, onError: error => notify.error("Device pairing failed", error.message) });
  const config = pairing ? JSON.stringify({ endpointBaseUrl: window.location.origin, deviceToken: pairing.deviceToken, encryptionKey: pairing.encryptionKey }, null, 2) : "";
  const copy = async () => { await navigator.clipboard.writeText(config); notify.info("Pairing file copied", "Save it as vaultline-pairing.json, then choose a local folder with sync.mjs configure."); };
  return <Dialog open={open} onOpenChange={value => { setOpen(value); if (!value) { setPairing(null); setName(""); } }}><DialogTrigger asChild><Button><Link2 className="mr-2 h-4 w-4" />Pair local device</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{pairing ? "Save the pairing file" : "Pair a local companion"}</DialogTitle><DialogDescription>{pairing ? "This is the only time the device token and encryption key will be shown. Store the file only on the paired computer, then use sync.mjs configure to choose the folder to monitor." : "Create a device-specific encrypted connection for one local computer."}</DialogDescription></DialogHeader>{pairing ? <div className="space-y-4"><pre className="max-h-80 overflow-auto rounded-xl bg-[#14213d] p-4 text-xs leading-5 text-[#dcecff]">{config}</pre><div className="rounded-xl bg-[#f4f8fd] px-4 py-3 text-xs leading-5 text-[#58708d]">Next, run <span className="font-mono text-[#294f78]">node sync.mjs configure --pairing vaultline-pairing.json --config vaultline-companion.json</span> on the local computer to select the folder.</div><div className="flex gap-3"><Button onClick={copy} className="flex-1"><Clipboard className="mr-2 h-4 w-4" />Copy pairing JSON</Button><Button variant="outline" onClick={() => setOpen(false)}>Done</Button></div></div> : <div className="space-y-4 py-2"><div className="space-y-2"><Label htmlFor="device-name">Device name</Label><Input id="device-name" value={name} onChange={event => setName(event.target.value)} placeholder="My work laptop" /></div><Button className="w-full" disabled={!name.trim() || create.isPending} onClick={() => create.mutate({ name: name.trim() })}>Create pairing file</Button></div>}</DialogContent></Dialog>;
}
