import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { notify } from "@/lib/notify";
import { CalendarClock, Clock3, Pause, Play, Plus, Trash2 } from "lucide-react";
import { useState } from "react";

export default function SchedulesPage() {
  const schedules = trpc.backup.listSchedules.useQuery();
  const utils = trpc.useUtils();
  const update = trpc.backup.updateSchedule.useMutation({ onSuccess: (_schedule, input) => { utils.backup.listSchedules.invalidate(); notify.info(input.enabled ? "Schedule resumed" : "Schedule paused", "Your encrypted backup cadence has been updated."); }, onError: error => notify.error("Schedule could not be updated", error.message) });
  const remove = trpc.backup.deleteSchedule.useMutation({ onSuccess: () => { utils.backup.listSchedules.invalidate(); notify.success("Schedule removed", "No further automated snapshots will be created by this schedule."); }, onError: error => notify.error("Schedule could not be removed", error.message) });
  return <div className="mx-auto w-full max-w-7xl space-y-6"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold tracking-[0.14em] text-[#7291b9] uppercase">Automation</p><h1 className="mt-1 text-3xl font-semibold tracking-[-0.035em] text-[#1d2939]">Backup schedules</h1><p className="mt-2 text-sm text-[#748196]">Create user-managed, UTC cron schedules for encrypted snapshots.</p></div><CreateSchedule onCreated={() => utils.backup.listSchedules.invalidate()} /></div><Card className="border-[#e2e8f0] shadow-sm"><CardContent className="p-0">{schedules.data?.length ? <div className="divide-y divide-[#edf0f4]">{schedules.data.map(schedule => <div key={schedule.id} className="flex flex-col gap-4 px-5 py-5 lg:flex-row lg:items-center"><div className="rounded-xl bg-[#f0efff] p-3 text-[#5b48b3]"><CalendarClock className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-medium text-[#2a384c]">{schedule.name}</p><p className="mt-1 font-mono text-xs text-[#8390a3]">{schedule.cronExpression} UTC</p></div><div className="text-sm text-[#738197]">{schedule.nextRunAt ? `Next: ${new Date(schedule.nextRunAt).toLocaleString()}` : "Awaiting next run"}</div><Badge className={schedule.enabled ? "bg-[#eaf7ef] text-[#207347] hover:bg-[#eaf7ef]" : "bg-[#f1f3f6] text-[#6a778a] hover:bg-[#f1f3f6]"}>{schedule.enabled ? "Active" : "Paused"}</Badge><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => update.mutate({ scheduleId: schedule.id, enabled: !schedule.enabled })}>{schedule.enabled ? <Pause className="mr-1.5 h-3.5 w-3.5" /> : <Play className="mr-1.5 h-3.5 w-3.5" />}{schedule.enabled ? "Pause" : "Resume"}</Button><Button size="icon" variant="ghost" className="text-[#b64943] hover:bg-[#fff2f0] hover:text-[#b64943]" onClick={() => remove.mutate({ scheduleId: schedule.id })} aria-label="Delete schedule"><Trash2 className="h-4 w-4" /></Button></div></div>)}</div> : <div className="py-20 text-center"><Clock3 className="mx-auto h-8 w-8 text-[#9ba7b8]" /><p className="mt-4 font-medium text-[#42516a]">No schedules configured.</p><p className="mt-1 text-sm text-[#8592a5]">Choose a managed file and define its backup interval.</p></div>}</CardContent></Card></div>;
}

function CreateSchedule({ onCreated }: { onCreated: () => void }) {
  const [open, setOpen] = useState(false); const [fileId, setFileId] = useState(""); const [name, setName] = useState(""); const [cronExpression, setCronExpression] = useState("0 0 9 * * *");
  const files = trpc.backup.listFiles.useQuery(); const create = trpc.backup.createSchedule.useMutation({ onSuccess: () => { onCreated(); setOpen(false); setFileId(""); setName(""); notify.success("Schedule created", "Your automated encrypted backups are now configured."); }, onError: error => notify.error("Schedule could not be created", error.message) });
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4" />New schedule</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create backup schedule</DialogTitle><DialogDescription>Schedules use six-field UTC cron expressions. Seconds must be set to 0.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><div className="space-y-2"><Label htmlFor="schedule-name">Name</Label><Input id="schedule-name" value={name} onChange={event => setName(event.target.value)} placeholder="Daily project archive" /></div><div className="space-y-2"><Label>Managed file</Label><Select value={fileId} onValueChange={setFileId}><SelectTrigger><SelectValue placeholder="Select a file" /></SelectTrigger><SelectContent>{files.data?.map(file => <SelectItem key={file.id} value={String(file.id)}>{file.displayName}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="cron">Cron expression</Label><Input id="cron" value={cronExpression} onChange={event => setCronExpression(event.target.value)} className="font-mono" /><p className="text-xs text-muted-foreground">Example: <span className="font-mono">0 0 9 * * *</span> runs daily at 09:00 UTC.</p></div><Button className="w-full" disabled={!fileId || !name.trim() || create.isPending} onClick={() => create.mutate({ fileId: Number(fileId), name: name.trim(), cronExpression })}>Create schedule</Button></div></DialogContent></Dialog>;
}
